#!/usr/bin/env bash
# This script prints number from "1-100", prints fizz when number is a multiple of 3 buzz when it's a multiple of 5 prints FiBuzz when it's a muliple of 3 and 5

number=1
for ((number = 1; number <= 100; number++)); do
if ((number % 15 == 0)); then
echo "FizzBuzz"
elif ((number % 3 == 0)); then
echo "Fizz"
elif ((number % 5 == 0)); then
echo "Buzz"
else
echo "$number"
fi
done
