#!/usr/bin/env bash
# Nginx configuration to listen on th same port

server {
    listen 80;
    server_name 54.89.182.154;  # Replace with your domain name

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;  # Replace with your application server address and port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

