#!/usr/bin/env bash
# Nginx configuration script to serve the route found in web_dynamic/2-hbnb of Airbnb-clone_v4

server {
        listen 80 default_server;
        listen [::]:80 default_server;

	# use either ip address or your domain name as server_name
        server_name 54.89.182.154

        # Customize HTTP response header
        add_header X-Served-By 304102-web-01;

	# Configure Nginx so that the route / Airbnb-clone_v4/web_dynamic/2-hbnb.py
        # points to your Gunicorn instance
        locaton / {
                proxy_pass http://127.0.0.1:5003/2-hbnb;
        }

        # Serve Static content from Airbnb-clone_v4
        location /static/ {
        alias web_dynamic/static/;
        }

	error_page 404 /404.hml;
        location /404 {
        root /var/www/html;
        internal;
        }
}
